name: train-my-deepfake

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          sh git-setup.sh
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: output.mp4
          
